version: "3"
services:
  system-test:
    build: .
    links:
      - system-under-test
    environment:
      - "ROS_MASTER_URI=http://system-under-test:11311"
  system-under-test:
    build:
      context: ..
      args:
        GITHUB_LOGIN: "${GITHUB_LOGIN}"
        GITHUB_PASSWORD: "${GITHUB_PASSWORD}"
    command: bash -c "source /opt/ros/kinetic/setup.bash && roscore"
