version: "3"
services:
  system-test:
    build: .
    links:
      - system-under-test
    environment:
      - "ROS_MASTER_URI=http://system-under-test:11311"
  system-under-test:
    image: ${TEST_BUILD_TAG}_system-under-test
    command: bash -c "source /opt/ros/kinetic/setup.bash && roscore"
